export const sampleMenuItems = [
    {
        id: '1',
        name: 'Classic Beef Burger',
        description: 'Juicy beef patty with lettuce, tomato, onion, and our special sauce',
        price: 15.99,
        category: 'burgers',
        image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
        type: 'Non Veg' as const,
        available: true,
        preparationTime: 12,
        ingredients: ['Beef patty', 'Lettuce', 'Tomato', 'Onion', 'Special sauce', 'Sesame bun'],
        allergens: ['Gluten', 'Dairy']
    },
    {
        id: '2',
        name: 'Margherita Pizza',
        description: 'Classic pizza with fresh mozzarella, tomato sauce, and basil',
        price: 18.99,
        category: 'pizzas',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
        type: 'Veg' as const,
        available: true,
        preparationTime: 15,
        ingredients: ['Pizza dough', 'Tomato sauce', 'Mozzarella', 'Fresh basil'],
        allergens: ['Gluten', 'Dairy']
    },
    {
        id: '3',
        name: 'Caesar Salad',
        description: 'Crisp romaine lettuce with Caesar dressing, croutons, and parmesan',
        price: 12.99,
        category: 'salads',
        image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400',
        type: 'Veg' as const,
        available: true,
        preparationTime: 8,
        ingredients: ['Romaine lettuce', 'Caesar dressing', 'Croutons', 'Parmesan cheese'],
        allergens: ['Dairy', 'Eggs']
    },
    {
        id: '4',
        name: 'Grilled Chicken Tacos',
        description: 'Three soft tacos with grilled chicken, salsa, and avocado',
        price: 14.99,
        category: 'mains',
        image: 'https://images.unsplash.com/photo-1565299585323-38174c8e3c15?w=400',
        type: 'Non Veg' as const,
        available: true,
        preparationTime: 10,
        ingredients: ['Grilled chicken', 'Soft tortillas', 'Salsa', 'Avocado', 'Cilantro'],
        allergens: ['Gluten']
    },
    {
        id: '5',
        name: 'Fresh Orange Juice',
        description: 'Freshly squeezed orange juice with pulp',
        price: 6.99,
        category: 'beverages',
        image: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=400',
        type: 'Veg' as const,
        available: true,
        preparationTime: 3,
        ingredients: ['Fresh oranges'],
        allergens: []
    },
    {
        id: '6',
        name: 'Chocolate Lava Cake',
        description: 'Warm chocolate cake with molten center, served with vanilla ice cream',
        price: 8.99,
        category: 'desserts',
        image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400',
        type: 'Veg' as const,
        available: true,
        preparationTime: 12,
        ingredients: ['Dark chocolate', 'Butter', 'Eggs', 'Flour', 'Vanilla ice cream'],
        allergens: ['Gluten', 'Dairy', 'Eggs']
    },
    {
        id: '7',
        name: 'Fish and Chips',
        description: 'Beer-battered fish with crispy fries and tartar sauce',
        price: 16.99,
        category: 'mains',
        image: 'https://images.unsplash.com/photo-1544982503-9f984c14501a?w=400',
        type: 'Non Veg' as const,
        available: true,
        preparationTime: 18,
        ingredients: ['Fresh fish', 'Beer batter', 'Potatoes', 'Tartar sauce'],
        allergens: ['Gluten', 'Fish']
    },
    {
        id: '8',
        name: 'Vegetable Spring Rolls',
        description: 'Crispy spring rolls filled with fresh vegetables, served with sweet chili sauce',
        price: 9.99,
        category: 'appetizers',
        image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400',
        type: 'Veg' as const,
        available: true,
        preparationTime: 8,
        ingredients: ['Mixed vegetables', 'Spring roll wrapper', 'Sweet chili sauce'],
        allergens: ['Gluten']
    },
    {
        id: '9',
        name: 'Iced Coffee',
        description: 'Cold brew coffee served over ice with milk',
        price: 5.99,
        category: 'beverages',
        image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400',
        type: 'Veg' as const,
        available: true,
        preparationTime: 5,
        ingredients: ['Cold brew coffee', 'Ice', 'Milk'],
        allergens: ['Dairy']
    },
    {
        id: '10',
        name: 'BBQ Ribs',
        description: 'Tender pork ribs with smoky BBQ sauce and coleslaw',
        price: 22.99,
        category: 'mains',
        image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400',
        type: 'Non Veg' as const,
        available: true,
        preparationTime: 25,
        ingredients: ['Pork ribs', 'BBQ sauce', 'Coleslaw', 'French fries'],
        allergens: ['Dairy']
    }
]

export const sampleCategories = [
    { id: 'all', name: 'All Items', icon: 'Grid' },
    { id: 'appetizers', name: 'Appetizers', icon: 'Soup' },
    { id: 'mains', name: 'Main Course', icon: 'ChefHat' },
    { id: 'desserts', name: 'Desserts', icon: 'Cake' },
    { id: 'beverages', name: 'Beverages', icon: 'Coffee' },
    { id: 'salads', name: 'Salads', icon: 'Apple' },
    { id: 'burgers', name: 'Burgers', icon: 'Sandwich' },
    { id: 'pizzas', name: 'Pizzas', icon: 'Pizza' }
]